/* FTMA: season end + 2-day loan processing controls */
(function(){
  const URL='https://iloanplyuatfcwzovbpb.supabase.co',KEY='sb_publishable_oPXhOaLIGK05Ehw-o6jDsw_TKJODpjK';
  function boot(){
    if(!window.supabase||!document.querySelector('.admin-grid'))return false;
    if(document.getElementById('ftmaSeasonTools'))return true;
    const db=window.supabase.createClient(URL,KEY),token=()=>sessionStorage.getItem('ftma_admin_token')||'';
    const sec=document.createElement('section');sec.id='ftmaSeasonTools';sec.className='admin-card admin-wide';
    sec.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap"><div><p class="eyebrow">SEASON CONTROL</p><h2>시즌 운영</h2><div id="ftmaSeasonState" style="font-size:15px;font-weight:800;margin-top:7px">상태 확인 중...</div><div id="ftmaLoanDeadline" style="color:#999;font-size:10px;margin-top:6px"></div></div><button id="ftmaSeasonEndBtn" class="primary-btn" type="button" style="width:auto;min-width:150px">시즌 종료</button></div><p style="color:#85817a;font-size:10px;line-height:1.7;margin-top:14px">시즌 종료 시 이적시장을 닫고 종료 시점부터 2일 동안 임대 선수 처리를 진행합니다. 일반 임대 / 완전이적 옵션 임대 / 필수 이적 임대를 구분합니다.</p><div id="ftmaLoanList" style="margin-top:18px"></div>';
    const grid=document.querySelector('.admin-grid');const first=grid.querySelector('.window-card');if(first&&first.nextSibling)grid.insertBefore(sec,first.nextSibling);else grid.appendChild(sec);
    function dialog(title,text){return new Promise(resolve=>{const r=document.createElement('div');r.style.cssText='position:fixed;inset:0;z-index:10000;background:rgba(0,0,0,.72);display:grid;place-items:center;padding:20px';r.innerHTML=`<div style="width:min(440px,100%);background:#111315;border:1px solid #514731;padding:25px"><p class="eyebrow">FTMA MANAGEMENT</p><h3>${title}</h3><p style="color:#aaa;font-size:11px;line-height:1.7">${text}</p><div style="display:flex;justify-content:flex-end;gap:8px;margin-top:20px"><button type="button" data-no>취소</button><button type="button" class="primary-btn" data-yes>시즌 종료</button></div></div>`;document.body.appendChild(r);r.querySelector('[data-no]').onclick=()=>{r.remove();resolve(false)};r.querySelector('[data-yes]').onclick=()=>{r.remove();resolve(true)}})}
    async function load(){const {data}=await db.from('site_settings').select('key,value').in('key',['current_season','season_status','loan_processing_deadline']);const m=Object.fromEntries((data||[]).map(x=>[x.key,x.value]));const ended=m.season_status==='ended';document.getElementById('ftmaSeasonState').textContent=`${m.current_season||'현재'} 시즌 · ${ended?'종료':'진행 중'}`;document.getElementById('ftmaLoanDeadline').textContent=m.loan_processing_deadline?`임대 처리 마감: ${new Date(m.loan_processing_deadline).toLocaleString('ko-KR')}`:'시즌 종료 전';document.getElementById('ftmaSeasonEndBtn').disabled=ended;const {data:ps}=await db.from('players').select('id,name,current_club_name,is_loan,loan_type,loan_buy_option_fee,loan_mandatory_fee').eq('is_loan',true).order('name');const box=document.getElementById('ftmaLoanList');if(!ps?.length){box.innerHTML='<div style="color:#777;font-size:10px">현재 임대 중인 선수가 없습니다.</div>';return}box.innerHTML='<div style="font-size:14px;font-weight:800;margin-bottom:10px">임대 선수 처리 대상</div>'+ps.map(p=>{const typ=p.loan_type==='mandatory'?'필수 이적 임대':p.loan_type==='option'?'완전이적 옵션 임대':'일반 임대';const fee=p.loan_type==='mandatory'?p.loan_mandatory_fee:p.loan_type==='option'?p.loan_buy_option_fee:null;return `<div style="border-top:1px solid #2b2e32;padding:12px 0"><b>${String(p.name||'').replace(/[&<>]/g,'')}</b><span style="color:#888;font-size:10px"> · ${typ} · ${p.current_club_name||'미상'}${fee!=null?' · €'+Number(fee).toFixed(1)+'M':''}</span></div>`}).join('')}
    document.getElementById('ftmaSeasonEndBtn').onclick=async()=>{if(!(await dialog('시즌을 종료할까요?','시즌 종료 즉시 이적시장이 닫히고, 지금부터 2일간 임대 선수 처리가 가능합니다.')))return;const b=document.getElementById('ftmaSeasonEndBtn');b.disabled=true;try{const {data,error}=await db.rpc('ftma_admin_season_end',{p_token:token()});if(error)throw error;if(!data?.success)throw new Error(data?.code||'시즌 종료 실패');await load()}catch(e){b.disabled=false;const m=document.createElement('div');m.textContent=e.message||'시즌 종료 처리에 실패했습니다.';m.style.cssText='position:fixed;right:20px;bottom:20px;z-index:10001;background:#17191c;border:1px solid #8d4e4a;color:#f1aaa4;padding:12px 16px';document.body.appendChild(m);setTimeout(()=>m.remove(),3000)}};load();return true;
  }
  if(!boot()){let n=0;const t=setInterval(()=>{if(boot()||++n>100)clearInterval(t)},100)}
})();