const AB_URL='https://iloanplyuatfcwzovbpb.supabase.co';
const AB_KEY='sb_publishable_oPXhOaLIGK05Ehw-o6jDsw_TKJODpjM';
const AB_RPC=AB_URL+'/rest/v1/rpc/ftma_admin_mutate';
const abEsc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const abToken=()=>sessionStorage.getItem('ftma_admin_token')||'';
async function abGet(url){const r=await fetch(url,{headers:{apikey:AB_KEY,Authorization:`Bearer ${AB_KEY}`},cache:'no-store'});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{}if(!r.ok)throw new Error(d?.message||t||`HTTP ${r.status}`);return d||[]}
async function abMutate(id,payload){const token=abToken();if(!token)throw new Error('관리자 세션이 만료되었습니다. 다시 로그인해주세요.');const r=await fetch(AB_RPC,{method:'POST',headers:{apikey:AB_KEY,Authorization:`Bearer ${AB_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({p_token:token,p_table:'clubs',p_operation:'update',p_id:id,p_payload:payload}),cache:'no-store'});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{}if(!r.ok)throw new Error(d?.message||t||`HTTP ${r.status}`);return d}
const abStyle=document.createElement('style');
abStyle.textContent=`.budget-card{margin-top:18px}.budget-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.budget-total{color:#caa968;font-size:10px;letter-spacing:1px;white-space:nowrap}.budget-help{color:#77736c;font-size:10px;line-height:1.6}.budget-tools{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0 10px}.budget-search{flex:1 1 260px;min-width:220px;background:#090b0d;border:1px solid #303338;color:#eee;padding:11px}.budget-list{border-top:1px solid #2b2e32}.budget-row{display:grid;grid-template-columns:minmax(220px,1fr) 180px 100px;gap:14px;align-items:center;padding:14px 0;border-bottom:1px solid #27292d}.budget-club{display:flex;align-items:center;gap:12px;min-width:0}.budget-logo{width:42px;height:42px;object-fit:contain;border:1px solid #3d3930;background:#090a0b;border-radius:50%;flex:none}.budget-club b,.budget-club small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.budget-club small{margin-top:5px;color:#77736c;font-size:9px}.budget-input{width:100%;box-sizing:border-box;background:#090b0d;border:1px solid #303338;color:#eee;padding:10px}.budget-save{border:1px solid #8e713d;background:#17140e;color:#e4c987;padding:9px 12px;cursor:pointer}.budget-save:disabled{opacity:.5;cursor:wait}.budget-status{min-height:18px;margin-top:12px;color:#8f8b84;font-size:9px}.budget-status.ok{color:#86c99c}.budget-status.error{color:#d87567}.budget-modal{position:fixed;inset:0;z-index:10002;background:rgba(0,0,0,.84);display:grid;place-items:center;padding:20px}.budget-modal-card{position:relative;width:min(520px,100%);background:#111315;border:1px solid #514731;padding:28px}.budget-modal-card h2{margin:0 0 8px}.budget-modal-card p{color:#77736c;font-size:10px;line-height:1.6}.budget-modal-card label{display:block;color:#aaa69e;font-size:9px;margin-top:18px}.budget-modal-card input{width:100%;box-sizing:border-box;margin-top:7px;background:#090b0d;border:1px solid #303338;color:#eee;padding:12px}.budget-modal-actions{display:flex;justify-content:flex-end;gap:9px;margin-top:20px}.budget-modal-x{position:absolute;right:14px;top:10px;border:0;background:transparent;color:#aaa;font-size:24px;cursor:pointer}@media(max-width:700px){.budget-row{grid-template-columns:1fr}.budget-save{width:100%}}`;
document.head.appendChild(abStyle);
let abClubs=[];
async function abLoad(){
 try{abClubs=await abGet(`${AB_URL}/rest/v1/clubs?select=id,name,country,league,logo_url,transfer_budget,transfer_spent&order=name`);abRender();}
 catch(e){const box=document.getElementById('adminBudgetManager');if(box){box.innerHTML=`<div class="budget-status error">구단 자금 데이터를 불러오지 못했습니다: ${abEsc(e.message)}</div>`}}
}
function abRender(){
 let box=document.getElementById('adminBudgetManager');
 if(!box){box=document.createElement('section');box.id='adminBudgetManager';box.className='admin-card admin-wide budget-card';document.querySelector('.admin-grid')?.appendChild(box)}
 box.innerHTML=`<div class="budget-head"><div><p class="eyebrow">CLUB FINANCE CONTROL</p><h2>구단 이적 자금 관리</h2><p class="budget-help">모든 등록 구단의 가용 이적 자금을 직접 수정합니다. 저장한 금액은 구단 DB에 반영되며 구단 이적 협상 화면의 가용 이적자금과 즉시 연결됩니다.</p></div><span class="budget-total">${abClubs.length} CLUBS</span></div><div class="budget-tools"><input id="budgetSearch" class="budget-search" placeholder="구단명 검색"><button id="budgetRefresh" class="edit-btn" type="button">새로고침</button></div><div id="budgetList" class="budget-list"></div><div id="budgetStatus" class="budget-status"></div>`;
 document.getElementById('budgetSearch').addEventListener('input',abDrawRows);
 document.getElementById('budgetRefresh').onclick=abLoad;
 abDrawRows();
}
function abDrawRows(){
 const q=(document.getElementById('budgetSearch')?.value||'').trim().toLowerCase();
 const list=abClubs.filter(c=>!q||String(c.name||'').toLowerCase().includes(q));
 const box=document.getElementById('budgetList');if(!box)return;
 box.innerHTML=list.length?list.map(c=>`<div class="budget-row"><div class="budget-club">${c.logo_url?`<img class="budget-logo" src="${abEsc(c.logo_url)}" alt="">`:''}<div><b>${abEsc(c.name)}</b><small>${abEsc(c.country||'')} · ${abEsc(c.league||'')} · 현재 €${Number(c.transfer_budget||0).toFixed(Number(c.transfer_budget)%1?'1':'0')}M</small></div></div><div><input class="budget-input" data-budget-id="${abEsc(c.id)}" type="number" min="0" step="0.1" value="${Number(c.transfer_budget||0)}" aria-label="${abEsc(c.name)} 이적 자금"></div><button class="budget-save" type="button" data-budget-save="${abEsc(c.id)}">저장</button></div>`).join(''):'<div class="loading">검색 결과가 없습니다.</div>';
 box.querySelectorAll('[data-budget-save]').forEach(btn=>btn.onclick=()=>abOpenEditor(btn.dataset.budgetSave));
}
function abOpenEditor(id){
 const c=abClubs.find(x=>x.id===id);if(!c)return;
 const row=document.querySelector(`[data-budget-id="${CSS.escape(id)}"]`);const value=row?.value??Number(c.transfer_budget||0);
 const m=document.createElement('div');m.className='budget-modal';m.innerHTML=`<form class="budget-modal-card"><button type="button" class="budget-modal-x">×</button><p class="eyebrow">CLUB FINANCE</p><h2>${abEsc(c.name)} 이적 자금 수정</h2><p>현재 가용 이적 자금: <b>€${Number(c.transfer_budget||0).toFixed(Number(c.transfer_budget)%1?'1':'0')}M</b><br>새 금액을 입력하면 이 구단의 DB 값이 변경됩니다.</p><label>가용 이적 자금 (€M)<input name="budget" type="number" min="0" step="0.1" value="${abEsc(value)}"></label><div class="budget-modal-actions"><button type="button" class="ghost-btn" data-cancel>취소</button><button type="button" class="primary-btn" data-save>자금 저장</button></div><div class="budget-status" data-error></div></form>`;
 document.body.appendChild(m);const close=()=>m.remove();m.querySelector('.budget-modal-x').onclick=close;m.querySelector('[data-cancel]').onclick=close;
 m.querySelector('[data-save]').onclick=async()=>{const b=m.querySelector('[data-save]'),e=m.querySelector('[data-error]');const n=Number(m.querySelector('[name=budget]').value);if(!Number.isFinite(n)||n<0){e.className='budget-status error';e.textContent='0 이상의 올바른 금액을 입력해주세요.';return}b.disabled=true;b.textContent='저장 중...';e.textContent='';try{await abMutate(id,{transfer_budget:n});const idx=abClubs.findIndex(x=>x.id===id);if(idx>=0)abClubs[idx].transfer_budget=n;close();abDrawRows();const s=document.getElementById('budgetStatus');if(s){s.className='budget-status ok';s.textContent=`${c.name}의 이적 자금을 €${n.toFixed(n%1?'1':'0')}M로 저장했습니다.`}if(typeof window.messageF==='function')window.messageF(`${c.name}의 이적 자금이 수정되었습니다.`)}catch(x){e.className='budget-status error';e.textContent=x.message;b.disabled=false;b.textContent='자금 저장'}};
}
function abBoot(){if(document.getElementById('adminApp'))setTimeout(abLoad,350);else setTimeout(abLoad,700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',abBoot);else abBoot();
