const API='/api/public-data?resource=home';
let players=[],clubs=[],news=[],transfers=[],homeSummary={};
const money=(v,c='EUR')=>`${c==='EUR'?'€':c==='GBP'?'£':'$'}${Number(v||0).toFixed(1)}M`;
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const img=(url,cls,alt)=>url?`<img class="${cls}" src="${esc(url)}" alt="${esc(alt||'')}" loading="lazy" decoding="async" onerror="this.style.visibility='hidden'">`:'';
const ageOf=p=>typeof window.ftmaAgeOr==='function'?window.ftmaAgeOr(p.birth_date,p.age??'유망주'):(p.age??'유망주');
async function getHome(){const key='ftma_home_snapshot_v3';try{const c=sessionStorage.getItem(key);if(c){const x=JSON.parse(c);if(Date.now()-x.at<120000)return x.data}}catch(_){}try{const r=await fetch(API,{cache:'default'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();try{sessionStorage.setItem(key,JSON.stringify({at:Date.now(),data}))}catch(_){}return data}catch(e){try{const c=sessionStorage.getItem(key);if(c)return JSON.parse(c).data}catch(_){}throw e}}
async function loadData(){try{const d=await getHome();players=d.players||[];clubs=d.clubs||[];news=d.news||[];transfers=d.transfers||[];homeSummary=d.summary||{};render(players,clubs);renderNews(news);renderTransfers(transfers)}catch(e){console.error('[FTMA home]',e);showError('FTMA 데이터베이스에 연결할 수 없습니다. 잠시 후 다시 시도해주세요')}}
function setText(id,value){const e=document.getElementById(id);if(e)e.textContent=value}
function render(ps,cs){const total=Number(homeSummary.market_value||0),pc=Number(homeSummary.players||ps.length),cc=Number(homeSummary.clubs||cs.length),u20=Number(homeSummary.u20||0);setText('playerCount',pc);setText('clubCount',cc);setText('u20Count',u20);setText('dashPlayers',pc);setText('dashClubs',cc);setText('dashU20',u20);setText('marketValue',money(total));setText('totalValue',money(total));const rows=document.getElementById('marketRows');if(rows)rows.innerHTML=ps.length?ps.map((p,i)=>`<a class="player-row" href="player.html?id=${encodeURIComponent(p.id)}"><div class="home-player-cell">${img(p.photo_url,'home-market-photo',p.name)}<span class="avatar">${String(i+1).padStart(2,'0')}</span><span><b>${esc(p.name)}</b><small>${esc(p.nationality||'미상')} · ${ageOf(p)}</small></span></div><span>${esc(p.position||'미정')}</span><span>${esc(p.clubs?.name||'미소속')}</span><strong>${money(p.market_value)}</strong></a>`).join(''):'<div class="loading">등록된 선수가 없습니다.</div>';const grid=document.getElementById('playerGrid');if(grid)grid.innerHTML=ps.slice(0,6).map(p=>`<a class="profile-card" href="player.html?id=${encodeURIComponent(p.id)}">${img(p.photo_url,'home-profile-photo',p.name)}<div class="rating">${p.ability??'—'}</div><span class="position">${esc(p.position||'미정')}</span><h3>${esc(p.name)}</h3><p>${esc(p.nationality||'미상')} • ${esc(p.clubs?.name||'미소속')}</p><div class="profile-meta"><span>나이 <b>${ageOf(p)}</b></span><span>어빌 <b>${p.ability??'—'}</b></span><span>포텐 <b>${p.potential??'—'}</b></span><span>시장가치 <b>${money(p.market_value)}</b></span></div></a>`).join('');const clubBox=document.getElementById('clubGrid');if(clubBox)clubBox.innerHTML=cs.map(c=>`<a class="club-card" href="club.html?id=${encodeURIComponent(c.id)}">${c.logo_url?img(c.logo_url,'home-club-logo',c.name+' 로고'):`<span>${esc((c.name||'FT').slice(0,2).toUpperCase())}</span>`}<div class="home-club-copy"><b>${esc(c.name)}</b><small>${esc(c.league||'판타지 리그')}</small></div></a>`).join('')}
function renderTransfers(ts){let box=document.getElementById('transferRows');if(!box){const section=document.createElement('section');section.className='portal-section section-pad dark-section transfer-section';section.innerHTML='<div class="section-heading"><div><p class="eyebrow">TRANSFER RECORDS</p><h2>최근 이적 기록</h2><p>관리자에서 등록된 공식 이적 기록이 메인에 실시간으로 연결됩니다.</p></div></div><div id="transferRows" class="transfer-list"></div>';const market=document.getElementById('market')?.closest('section');market?.after(section);box=document.getElementById('transferRows')}if(!box)return;if(!ts.length){box.innerHTML='<div class="loading">등록된 이적 기록이 없습니다.</div>';return}box.innerHTML=ts.map((t,i)=>{const fee=t.transfer_fee==null?'비공개':money(t.transfer_fee,t.fee_currency);const type=t.transfer_type==='loan'?'임대':t.transfer_type==='free'?'자유계약':t.transfer_type==='loan_return'?'임대 복귀':'완전 이적';const status=t.status==='official'?'공식':t.status==='pending'?'진행 중':t.status==='rumour'?'루머':'무산';return `<article class="transfer-row"><span class="transfer-no">${String(i+1).padStart(2,'0')}</span><div><b>${esc(t.players?.name||'알 수 없는 선수')}</b><small>${esc(t.from_club?.name||t.from_club_name||'미소속')} → ${esc(t.to_club?.name||t.to_club_name||'미소속')}</small></div><strong>${esc(fee)}</strong><span>${type}</span><em class="status ${t.status==='official'?'open':'hot'}">${status}</em><time>${new Date(t.transfer_date).toLocaleDateString('ko-KR')}</time></article>`}).join('')}
function renderNews(ns){const hero=document.getElementById('featuredNews'),image=document.getElementById('featuredImage'),side=document.getElementById('newsSideList');if(!hero)return;if(!ns.length){if(side)side.innerHTML='<div class="news-empty-side">아직 등록된 뉴스가 없습니다.</div>';return}const a=ns[0];hero.href=`news.html?id=${encodeURIComponent(a.id)}`;if(image)image.innerHTML=`<img src="${esc(a.cover_image_url||'')}" alt="${esc(a.title)}" loading="lazy" decoding="async">`;setText('featuredCategory',a.category||'FTMA NEWS');setText('featuredTitle',a.title);setText('featuredSummary',a.summary||'');const link=document.querySelector('#featuredNews strong');if(link)link.textContent='기사 전체보기 →';if(side)side.innerHTML=ns.slice(0,5).map((x,i)=>`<a href="news.html?id=${encodeURIComponent(x.id)}" class="news-side-item"><span>${String(i+1).padStart(2,'0')}</span><div><small>${esc(x.category||'FTMA NEWS')}</small><b>${esc(x.title)}</b><em>${new Date(x.published_at).toLocaleDateString('ko-KR')}</em></div></a>`).join('')}
function showError(msg){const box=document.getElementById('marketRows');if(box)box.innerHTML=`<div class="loading">${esc(msg)}</div>`}
if(document.getElementById('marketRows'))loadData();
