const SUPABASE_URL='https://iloanplyuatfcwzovbpb.supabase.co';
const SUPABASE_KEY='sb_publishable_oPXhOaLIGK05Ehw-o6jDsw_TKJODpjM';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const fallbackMark=name=>`<span class="club-mark-fallback">${esc((name||'FT').slice(0,2).toUpperCase())}</span>`;
function logoHtml(c){if(!c.logo_url)return fallbackMark(c.name);const src=esc(c.logo_url);return `<img class="club-logo" src="${src}" alt="${esc(c.name)} 로고" loading="lazy" decoding="async" referrerpolicy="no-referrer" onerror="this.onerror=null;this.replaceWith((()=>{const s=document.createElement('span');s.className='club-mark-fallback';s.textContent='${esc((c.name||'FT').slice(0,2).toUpperCase())}';return s})())">`}
async function getClubs(){const {data,error}=await db.from('clubs').select('id,name,country,league,description,logo_url').order('name');if(error)throw error;return data||[]}
async function getPlayers(){const {data,error}=await db.from('players').select('current_club_id');if(error)throw error;return data||[]}
function card(c,count){return `<a class="directory-club" href="club.html?id=${encodeURIComponent(c.id)}"><div class="club-mark">${logoHtml(c)}</div><div class="club-info"><h3>${esc(c.name)}</h3><p>${esc(c.league||'리그 미상')}</p>${c.description?`<small>${esc(c.description)}</small>`:''}</div><strong>${count}<small>명</small></strong></a>`}
function render(list,players){const box=document.getElementById('clubList');if(!box)return;document.getElementById('clubCount').textContent=`${list.length}구단`;if(!list.length){box.innerHTML='<div class="loading">검색 결과가 없습니다.</div>';return}const counts=new Map();for(const p of players) counts.set(p.current_club_id,(counts.get(p.current_club_id)||0)+1);box.innerHTML=list.map(c=>card(c,counts.get(c.id)||0)).join('')}
(async()=>{try{const [clubs,players]=await Promise.all([getClubs(),getPlayers()]);render(clubs,players);document.getElementById('clubSearch')?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();render(clubs.filter(c=>[c.name,c.country,c.league].some(v=>String(v||'').toLowerCase().includes(q))),players)})}catch(e){console.error('FTMA club page load failed',e);const box=document.getElementById('clubList');if(box)box.innerHTML='<div class="loading">데이터를 불러오지 못했습니다. 잠시 후 새로고침해 주세요.</div>'}})();