/* FTMA transfer-market-only search: stable client-side filter. */
(function(){
  let timer=0,lastRowCount=-1;
  function styles(){if(document.getElementById('ftmaMarketSearchStyles'))return;const s=document.createElement('style');s.id='ftmaMarketSearchStyles';s.textContent='.market-search-panel{display:flex;align-items:center;gap:14px;margin-top:24px;padding:14px 16px;border:1px solid #303338;background:#111315}.market-search-panel input{flex:1;min-width:0;background:#090b0d;border:1px solid #3a3d42;color:#eee;padding:13px 14px;outline:0;font-size:12px}.market-search-panel input:focus{border-color:#9b7c3e;box-shadow:0 0 0 2px rgba(202,169,104,.08)}.market-search-panel .market-search-label{color:#caa968;font-size:9px;font-weight:900;letter-spacing:.16em;white-space:nowrap}.market-search-panel .market-search-count{color:#8b877f;font-size:9px;white-space:nowrap}.market-search-hidden{display:none!important}.market-search-empty{padding:24px;text-align:center;color:#77736b}@media(max-width:700px){.market-search-panel{display:grid;grid-template-columns:1fr;gap:8px}.market-search-panel input{width:100%;box-sizing:border-box}.market-search-panel .market-search-count{display:none}}';document.head.appendChild(s)}
  function rows(){const list=document.getElementById('marketList');return list?Array.from(list.querySelectorAll('.market-directory-row')):[]}
  function filter(){const list=document.getElementById('marketList'),input=document.getElementById('marketPlayerSearch');if(!list||!input)return;const q=String(input.value||'').trim().toLocaleLowerCase('ko-KR'),rs=rows();let visible=0;rs.forEach(row=>{const hay=String(row.textContent||'').toLocaleLowerCase('ko-KR'),ok=!q||hay.includes(q);row.classList.toggle('market-search-hidden',!ok);if(ok)visible++});const count=document.getElementById('marketSearchCount');if(count)count.textContent=q?`${visible}명 검색됨 / ${rs.length}명`:`${rs.length}명 등록`;let empty=list.querySelector('.market-search-empty');if(!visible&&rs.length){if(!empty){empty=document.createElement('div');empty.className='market-search-empty';empty.textContent='검색 결과가 없습니다.';list.appendChild(empty)}empty.style.display='block'}else if(empty)empty.style.display='none'}
  function schedule(){clearTimeout(timer);timer=setTimeout(filter,40)}
  function install(){const list=document.getElementById('marketList'),heading=list?.closest('.directory-section')?.querySelector('.directory-heading');if(!list||!heading)return false;styles();let panel=document.getElementById('marketSearchPanel');if(!panel){panel=document.createElement('div');panel.id='marketSearchPanel';panel.className='market-search-panel';panel.innerHTML='<span class="market-search-label">MARKET SEARCH</span><input id="marketPlayerSearch" type="search" autocomplete="off" placeholder="이적시장 등록 선수 이름, 포지션, 국적 또는 구단 검색"><span id="marketSearchCount" class="market-search-count"></span>';heading.insertAdjacentElement('afterend',panel);const input=panel.querySelector('#marketPlayerSearch');input.addEventListener('input',schedule,{passive:true});input.addEventListener('search',schedule,{passive:true})}const count=rows().length;if(count!==lastRowCount){lastRowCount=count;filter()}return true}
  let attempts=0;function boot(){if(install())return;if(++attempts<100)setTimeout(boot,100)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();setInterval(()=>{const n=rows().length;if(n!==lastRowCount)install()},500);
})();
