const SUPABASE_URL='https://iloanplyuatfcwzovbpb.supabase.co';const SUPABASE_KEY='sb_publishable_oPXhOaLIGK05Ehw-o6jDsw_TKJODpjM';const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));const MAX=11;let players=[];let slots=[];let selectedSlot=null;const pitch=document.getElementById('pitch'),slotLayer=document.getElementById('slotLayer'),pool=document.getElementById('playerPool'),picker=document.getElementById('playerPicker'),search=document.getElementById('playerSearch'),readout=document.getElementById('formationReadout');
// 기본 포메이션은 4-3-3으로 유지한다. 2번 첨부는 배치 좌표가 아니라 FTMA 스쿼드 메이커의 외형/스타일 기준이다.
const defaults=[['LW',20,17],['ST',50,17],['RW',80,17],['CM',20,39],['CAM',50,39],['CM',80,39],['LB',17,68],['CB',39,68],['CB',61,68],['RB',83,68],['GK',50,89]];
function resetSlotPosition(slot){slot.x=defaults[slot.i][1];slot.y=defaults[slot.i][2]}
function initSlots(){slotLayer.innerHTML='';slots=defaults.map(([position,x,y],i)=>({i,position,x,y,player:null,el:null}));slots.forEach(renderSlot);updateCount()}
function renderSlot(slot){const el=document.createElement('button');el.type='button';el.className='player-slot empty-slot';el.style.left=slot.x+'%';el.style.top=slot.y+'%';el.dataset.slot=slot.i;el.innerHTML=`<span class="jersey-icon"><i>${esc(slot.position)}</i></span><strong>${esc(slot.position)}</strong>`;el.addEventListener('click',()=>openPicker(slot));slotLayer.appendChild(el);slot.el=el}
function renderFilled(slot){if(!slot.el)return;const p=slot.player;slot.el.className='player-slot filled-slot';slot.el.innerHTML=`<span class="player-photo">${p.photo_url?`<img src="${esc(p.photo_url)}" alt="${esc(p.name)}" onerror="this.style.visibility='hidden'">`:'<span class="photo-fallback">FTMA</span>'}</span><strong class="player-name">${esc(p.name)}</strong><small>${esc(p.position||slot.position)}</small>${p.is_loan?'<em class="player-loan-badge">임대</em>':''}<span class="remove-player" role="button" tabindex="0" aria-label="선수 제거" title="선수 제거"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 3h6l1 2h4v2H4V5h4l1-2zm-3 6h12l-.7 11.2a2 2 0 0 1-2 1.8H8.7a2 2 0 0 1-2-1.8L6 9zm3 2v8h2v-8H9zm4 0v8h2v-8h-2z"/></svg></span>`;makeDraggable(slot.el,slot);const remove=slot.el.querySelector('.remove-player');remove.addEventListener('pointerdown',e=>e.stopPropagation());remove.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();removePlayer(slot)});remove.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();removePlayer(slot)}});slot.el.addEventListener('click',e=>{if(e.target.closest('.remove-player'))return;if(slot.el.dataset.dragged==='1'){slot.el.dataset.dragged='0';return}openPicker(slot)})}
// 선수만 제거하고 슬롯의 현재 좌표는 그대로 둔다. 사용자가 옮긴 위치를 절대 기본 위치로 되돌리지 않는다.
function removePlayer(slot){slot.player=null;if(slot.el)slot.el.remove();renderSlot(slot);updateCount();updateFormation()}
function openPicker(slot){selectedSlot=slot;document.getElementById('pickerTitle').textContent='선수 선택';document.getElementById('pickerPosition').textContent=`${slot.position} 슬롯`;picker.classList.add('open');picker.setAttribute('aria-hidden','false');search.value='';renderPool(players);setTimeout(()=>search.focus(),50)}
function closePicker(){picker.classList.remove('open');picker.setAttribute('aria-hidden','true');selectedSlot=null}
document.getElementById('closePicker').addEventListener('click',closePicker);picker.addEventListener('click',e=>{if(e.target.matches('[data-close-picker]'))closePicker()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closePicker()});
async function loadPlayers(){const {data,error}=await db.from('players').select('id,name,photo_url,nationality,position,shirt_number,market_value,squad_type,is_loan,current_club_id,clubs(name)').order('name');if(error){pool.innerHTML='<div class="loading">선수 데이터를 불러오지 못했습니다.</div>';console.error(error);return}players=data||[];document.getElementById('playerPoolCount').textContent=`${players.length}명`;renderPool(players)}
function renderPool(list){const used=new Set(slots.filter(s=>s.player).map(s=>String(s.player.id)));pool.innerHTML=list.length?list.map(p=>{const u=used.has(String(p.id));return `<button type="button" class="pool-player" data-id="${esc(p.id)}" ${u?'disabled':''}><span class="pool-photo">${p.photo_url?`<img src="${esc(p.photo_url)}" alt="${esc(p.name)}" onerror="this.style.visibility='hidden'">`:'<i>FTMA</i>'}</span><span class="pool-player-copy"><b>${esc(p.name)} ${p.is_loan?'<em>임대</em>':''}</b><small>${esc(p.position||'미정')} · ${esc(p.nationality||'미상')} · ${esc(p.clubs?.name||'미소속')}</small></span><span class="pool-add">${u?'배치됨':'선택'}</span></button>`}).join(''):'<div class="loading">검색 결과가 없습니다.</div>'}
pool.addEventListener('click',e=>{const b=e.target.closest('button[data-id]');if(!b||b.disabled||!selectedSlot)return;const p=players.find(x=>String(x.id)===String(b.dataset.id));if(p){selectedSlot.player=p;renderFilled(selectedSlot);closePicker();updateCount();updateFormation()}});search.addEventListener('input',()=>{const q=search.value.trim().toLowerCase();renderPool(players.filter(p=>[p.name,p.position,p.nationality,p.clubs?.name].some(v=>String(v||'').toLowerCase().includes(q))))});
function makeDraggable(el,slot){let dragging=false,moved=false;const move=e=>{if(!dragging)return;moved=true;const r=pitch.getBoundingClientRect();slot.x=Math.max(5,Math.min(95,(e.clientX-r.left)/r.width*100));slot.y=Math.max(5,Math.min(95,(e.clientY-r.top)/r.height*100));el.style.left=slot.x+'%';el.style.top=slot.y+'%';updateFormation()};const up=()=>{if(!dragging)return;dragging=false;el.classList.remove('dragging');if(moved)el.dataset.dragged='1';window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};el.addEventListener('pointerdown',e=>{if(e.button!==undefined&&e.button!==0)return;if(e.target.closest('.remove-player'))return;dragging=true;moved=false;el.classList.add('dragging');window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)})}
function updateCount(){document.getElementById('squadCount').textContent=`${slots.filter(s=>s.player).length} / ${MAX}`}
function updateFormation(){const ys=slots.filter(s=>s.player).map(s=>s.y);if(ys.length<2){readout.textContent='4-3-3 · 기본 배치';return}const rows=[0,0,0,0];ys.forEach(y=>{if(y<28)rows[0]++;else if(y<58)rows[1]++;else if(y<78)rows[2]++;else rows[3]++});const active=rows.filter(Boolean);readout.textContent=active.length>=2?active.join('-')+' · 자동 분석':'CUSTOM FORMATION'}
document.getElementById('clearSquad').addEventListener('click',()=>{slots.forEach(s=>{s.player=null;resetSlotPosition(s);if(s.el)s.el.remove();renderSlot(s)});updateCount();updateFormation()});initSlots();loadPlayers();